# Use OpenJDK as the base image
FROM openjdk:17-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container
COPY ./build/libs/*.jar /app/stayeaseapp.jar

# Expose the application port
EXPOSE 8080

# Command to run the JAR file
CMD ["java", "-jar", "/app/stayeaseapp.jar"]